spring:
  profiles: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
management:
  add-application-context-header: false
  #
  # management.context-path
  # indicate the management context-path using random string for security
  #
  context-path: /__mgmt${random.value}__/
  #
  # management.address:
  # indicate the management endpoint binding address 127.0.0.1
  #
  #address: 127.0.0.1
  #
  # indicate the management endpoint listening port,
  # better differ from your application server port
  #
  # port: 8081
  security:
    roles: ADMIN
  # ssl:
    # key-store: config/admin-keystore.jks
    # key-store-password: keyStorePassword
    # trust-store: config/truststore.jks
    # trust-store-password: trustStorePassword
    #
    # client must offer its certificate,otherwise reject
    #
    # client-auth: need
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${server.port}-${random.long}

# SERVICE-1,SERVICE-2 as eureka service name
# force timeout to 30s
hystrix:
  command:
    SERVICE-1:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    SERVICE-2:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
